export interface Packout  {
    "wip_ID": number,
    "serialNumber": string,
    "customer_ID": number,
    "seqNumber": number,
    "panel_ID": number,
    "panel": number,
    "active": boolean,
    "purge": boolean,
    "referenceUnit": boolean,
    "referenceUnitActive": boolean,
    "scrap": boolean,
    "onHold": boolean,
    "currentlyOnHold": boolean,
    "rma": boolean,
    "rmaReturnCount": number,
    "deviation": boolean,
    "multiPartBarcode": string,
    "boardPanelBroken": boolean,
    "birthStatus": number,
    "userID_ID": number,
    "lastUpdated": string,
    "containerLinks": string[]
}